### ISSUE TITLE
"Nudge-move by Numerical Value" needs an update for Glyphs 2

### ISSUE THREAD

**Issue by mekkablue** [Tosche/Glyphs-Scripts#3]
If you run it in G2, you get:

    Nudge-move by Numerical Value Error: 'LayerSelectionProxy' object is not callable

**Comment by Tosche** [comment]
I have no problem using it. Is any node selected? (even without node selection it returns nothing)

**Comment by pocholito** [comment]
Hi Tosche.
I select a couple of nodes, run it and get this in the macro panel:
 GlyphsScripts/schriftgestalt_DrawBotGlyphsPlugin/DrawBot.glyphsPlugin/Contents/Resources/drawBot/context/__init__.pyc'>
__window <NSWindow: 0x7fc12107c360>
Start
End
Nudge-move by Numerical Value Error: '__LayerSelectionProxy' object is not callable

**Comment by Tosche** [comment]
That's the same error as mekkablue's, and I cannot replicate it. Could anybody make a pull request?
