### ISSUE TITLE
Got an error trying to use this plugin

### ISSUE THREAD

**Issue by megaghz** [Tosche/Glyphs-Scripts#4]
I got this error msg in console, when trying this script. I don't know what does it means. Thanks for your help.

`Start
Traceback (most recent call last):
  File "Instance Slider.py", line 14, in <module>
    for ins in font.instances:
AttributeError: 'NoneType' object has no attribute 'instances'
End
Start
End
Instance Slider Error (listClick): 'NoneType' object has no attribute 'previewInstances'
Start
Traceback (most recent call last):
  File "Instance Slider.py", line 273, in <module>
    InstanceSlider()
  File "Instance Slider.py", line 131, in __init__
    font.currentTab.previewInstances = 'live'
AttributeError: 'NoneType' object has no attribute 'previewInstances'
End
Instance Slider Error (listClick): 'NoneType' object has no attribute 'previewInstances'
Instance Slider Error (listClick): 'NoneType' object has no attribute 'previewInstances'
`

**Comment by Tosche** [comment]
This script uses functions that are only available from Glyphs 2.3. What version are you using?

**Comment by megaghz** [comment]
Version 2.3b (845)

**Comment by Tosche** [comment]
I noticed it doesn't open when there was no tab. I think I fixed it. Could you try?

**Comment by megaghz** [comment]
just replace this https://github.com/Tosche/Glyphs-Scripts/blob/master/Instance%20Slider.py ? 13 h ago

**Comment by Tosche** [comment]
No I updated it like 12 minutes ago.

**Comment by megaghz** [comment]
Working now, thanks!

**Comment by megaghz** [comment]
The preview isn't showing, in preview, text disappear when move the slides... they reappear in their default values.

**Comment by Tosche** [comment]
So, the only the master points are shown. That seems to mean your outlines are not compatible. How is it looking?

**Comment by megaghz** [comment]
just did some quick drawings to test... same nodes, dif position.

**Comment by Tosche** [comment]
Could you send your file to me? tosche@mac.com

**Comment by Tosche** [comment]
It was just an outline problem in the Glyphs file.
