### ISSUE TITLE
Duplicate Glyph with Component.py problem

### ISSUE THREAD

**Issue by designiq** [Tosche/Glyphs-Scripts#9]
Toshi, I am afraid this script Duplicate Glyph with Component.py does not work in the 2.4RC version. I would be very happy if you could by chance update it. Thanks!

**Comment by Tosche** [comment]
Hi Filip, sorry for the late response. I've tested the script now and it just works (the new glyphs go under "Other" and you need to update glyph info though). If you have encountered an error, there should be an error message in Macro window. Could you paste it here please?
